name: Build, Run Juice Shop, Generate SBOM, Scan with Semgrep, Detect Secrets with Gitleaks, Run ZAP Baseline and Dummy Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t juice-shop .

    - name: Run Juice Shop container
      run: |
        docker run -d -p 3000:3000 --name juice-shop-container juice-shop

    - name: Check if Juice Shop is running
      run: |
        sleep 10
        curl --fail http://localhost:3000 || exit 1

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SBOM as JSON with Syft
      run: |
        syft juice-shop -o json > sbom.json

    - name: Display SBOM JSON output
      run: |
        cat sbom.json

    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom-json
        path: sbom.json

    - name: Install Semgrep
      run: |
        pip install semgrep

    - name: Run Semgrep Scan (SARIF)
      run: |
        semgrep --config auto --sarif --output semgrep-results.sarif

    - name: Upload Semgrep Results (SARIF)
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-sarif-results
        path: semgrep-results.sarif

    - name: Install Gitleaks
      run: |
        curl -sL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
        chmod +x gitleaks
        mv gitleaks /usr/local/bin/

    - name: Run Gitleaks Scan (SARIF)
      run: |
        gitleaks detect --source . --report-format sarif --report-path gitleaks-results.sarif || true

    - name: Upload Gitleaks Results (SARIF)
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-sarif-results
        path: gitleaks-results.sarif

    - name: Run OWASP ZAP Baseline Scan
      run: |
        mkdir zap-report
        docker run --rm -v $(pwd)/zap-report:/zap/wrk/:rw owasp/zap2docker-stable zap-baseline.py -t http://example.com -r zap_report.html || true

    - name: Upload ZAP Baseline Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-baseline-report
        path: zap-report/zap_report.html

    - name: Dummy Deploy Step
      run: |
        echo "Deploying Juice Shop... (Dummy Deploy Step Executed)"
