name: Build, Run Juice Shop, Generate SBOM, and Scan with Semgrep

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-run-sbom-semgrep:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t juice-shop .

    - name: Run Juice Shop container
      run: |
        docker run -d -p 3000:3000 --name juice-shop-container juice-shop

    - name: Check if Juice Shop is running
      run: |
        sleep 10
        curl --fail http://localhost:3000 || exit 1

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SBOM as JSON with Syft
      run: |
        syft juice-shop -o json > sbom.json

    - name: Display SBOM JSON output
      run: |
        cat sbom.json

    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom-json
        path: sbom.json

    - name: Install Semgrep
      run: |
        curl -sL https://semgrep.dev/install.sh | bash

    - name: Run Semgrep SAST Scan and Generate SARIF
      run: |
        mkdir -p semgrep-results
        ./semgrep scan --config auto --sarif > semgrep-results/semgrep.sarif

    - name: Upload Semgrep SARIF artifact
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-sarif
        path: semgrep-results/semgrep.sarif
